#!/usr/bin/env python3
"""The command-policy fixture is frozen.

`testdata/command-parity.tsv` used to be regenerated by importing DevCouncil's
Python `TaskPolicyEngine`. That package has been deleted. This script refuses
to import it, refuses `DEVCOUNCIL_SRC`, and does not rewrite the TSV.

The committed file is the snapshot the Go command gate is held to, including
the named divergences in its header. Edit the TSV only when Go policy itself
changes, and say so in the commit. The live engine is DevCouncil's Go policy
(`backend/go_orchestrator/policy`), which Manvi links.
"""

from __future__ import annotations

import os
import sys


def main() -> int:
    if os.environ.get("DEVCOUNCIL_SRC"):
        print(
            "DEVCOUNCIL_SRC is set, but the Python devcouncil package is deleted "
            "and is not a generator for testdata/command-parity.tsv.",
            file=sys.stderr,
        )
    print(
        "scripts/gen-command-parity.py no longer imports the deleted Python "
        "devcouncil package.\n"
        "testdata/command-parity.tsv is a frozen snapshot of command-policy "
        "decisions (including documented divergences from the retired Python "
        "engine). It is not regenerated from Python.\n"
        "The live gate is DevCouncil Go policy "
        "(backend/go_orchestrator/policy), which Manvi links.",
        file=sys.stderr,
    )
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
