package policy

import (
	"os"
	"strings"
	"testing"

	"manvi/dc"
)

// parityFixture is generated by running DevCouncil's own TaskPolicyEngine over
// a corpus. Regenerate with scripts/gen-command-parity.py.
const parityFixture = "../../testdata/command-parity.tsv"

// These must match the fixture header. If the generator's corpus changes, the
// header comment in the .tsv records what it used.
var (
	parityTaskAllowed   = []string{"pytest *", "go test *", "make build", ".venv/bin/dev *"}
	parityGlobalAllowed = []string{"npm install"}
)

func parityTask() *dc.Task {
	return &dc.Task{ID: "TASK-001", Title: "parity", AllowedCommands: parityTaskAllowed}
}

type parityRow struct {
	section string
	command string
	want    string
	line    int
}

func loadParity(t *testing.T) []parityRow {
	t.Helper()
	raw, err := os.ReadFile(parityFixture)
	if err != nil {
		t.Fatalf("read command parity fixture: %v", err)
	}
	var rows []parityRow
	for i, line := range strings.Split(string(raw), "\n") {
		if strings.HasPrefix(line, "#") || strings.TrimSpace(line) == "" {
			continue
		}
		cols := strings.Split(line, "\t")
		if len(cols) != 3 {
			t.Fatalf("line %d is malformed: %q", i+1, line)
		}
		rows = append(rows, parityRow{cols[0], cols[1], cols[2], i + 1})
	}
	if len(rows) < 200 {
		t.Fatalf("only %d parity rows loaded from %s", len(rows), parityFixture)
	}
	return rows
}

// TestCommandParityWithPythonEngine is the port's correctness gate. Every rung
// of the ladder and every normalisation quirk is compared against what the
// incumbent actually decided, rather than against what the port's author
// believed it decided.
func TestCommandParityWithPythonEngine(t *testing.T) {
	rows := loadParity(t)

	// HardRules is false so the allowlist ladder is compared in isolation,
	// exactly matching Python's evaluate_command. Git safety is compared
	// separately below, against evaluate_hook_command.
	allowGate := CommandGate{GlobalAllowedCommands: parityGlobalAllowed, HardRules: false}

	counts := map[string]int{}
	for _, row := range rows {
		counts[row.section]++
		switch row.section {
		case "NORM":
			if got := NormalizeAllowlistCommand(row.command); got != row.want {
				t.Errorf("line %d: NormalizeAllowlistCommand(%q) = %q, want %q",
					row.line, row.command, got, row.want)
			}
		case "ALLOW_TASK":
			got := allowGate.EvaluateCommand(row.command, parityTask())
			if string(got.Action) != row.want {
				t.Errorf("line %d: EvaluateCommand(%q, task) = %s (%s), want %s",
					row.line, row.command, got.Action, got.Rule, row.want)
			}
		case "ALLOW_NOTASK":
			got := allowGate.EvaluateCommand(row.command, nil)
			if string(got.Action) != row.want {
				t.Errorf("line %d: EvaluateCommand(%q, nil) = %s (%s), want %s",
					row.line, row.command, got.Action, got.Rule, row.want)
			}
		case "GIT":
			got := GitSafety(row.command)
			if string(got.Action) != row.want {
				t.Errorf("line %d: GitSafety(%q) = %s (%s), want %s",
					row.line, row.command, got.Action, got.Rule, row.want)
			}
		default:
			t.Fatalf("line %d: unknown section %q", row.line, row.section)
		}
	}

	for _, section := range []string{"NORM", "ALLOW_TASK", "ALLOW_NOTASK", "GIT"} {
		if counts[section] == 0 {
			t.Errorf("fixture contained no %s rows", section)
		}
	}
}

// TestGitSafetyRunsEvenWhenTheAllowlistWouldPass is the one deliberate
// divergence from the incumbent, and it only ever tightens.
//
// The Python engine exposes the allowlist and git safety as separate entry
// points, so a caller that invokes only `evaluate_command` gets no git safety
// at all — and a task listing "git *" in allowed_commands would sail a
// force-push straight through. The port folds safety into the single entry
// point.
func TestGitSafetyRunsEvenWhenTheAllowlistWouldPass(t *testing.T) {
	permissive := &dc.Task{ID: "TASK-001", AllowedCommands: []string{"git *"}}
	gate := CommandGate{HardRules: true}

	forced := gate.EvaluateCommand("git push origin --force", permissive)
	if !forced.Blocked() || forced.Rule != RuleCommandForcePush {
		t.Fatalf("a force push must be denied even under `git *`, got %+v", forced)
	}
	if forced.Severity != Hard {
		t.Fatal("force push must be a hard rule; it can erase the evidence the gates reason about")
	}

	bypass := gate.EvaluateCommand("git commit --no-verify -m x", permissive)
	if !bypass.Blocked() || bypass.Rule != RuleCommandBypassFlag {
		t.Fatalf("a verification-bypass flag must be denied under `git *`, got %+v", bypass)
	}

	// An ordinary allowed git command still passes.
	ok := gate.EvaluateCommand("git status", permissive)
	if ok.Blocked() {
		t.Fatalf("git status should pass, got %+v", ok)
	}

	// A protected-branch push warns rather than blocks, matching the incumbent.
	warned := gate.EvaluateCommand("git push origin main", permissive)
	if warned.Action != Warn || warned.Rule != RuleCommandProtectedPush {
		t.Fatalf("a protected-branch push should warn, got %+v", warned)
	}
}

func TestEmptyCommandIsDeniedAndNotOverridable(t *testing.T) {
	d := CommandGate{HardRules: true}.EvaluateCommand("   ", nil)
	if !d.Blocked() || d.Rule != RuleCommandEmpty {
		t.Fatalf("expected an empty-command denial, got %+v", d)
	}
	if d.Overridable() {
		t.Fatal("there is nothing to grant for an empty command")
	}
}

func TestDisabledHardRulesIsRecordedOnCommandDecisions(t *testing.T) {
	d := CommandGate{HardRules: false}.EvaluateCommand("git status", nil)
	if len(d.Degraded) == 0 {
		t.Fatal("a decision made with hard rules off must record it")
	}
}

// TestRepoNamedDevCouncilIsNotRewritten guards the normalisation rule that only
// a bare dev binary, or one under bin/Scripts, collapses to "dev" — never a
// repository folder whose basename happens to match.
func TestRepoNamedDevCouncilIsNotRewritten(t *testing.T) {
	if got := NormalizeAllowlistCommand("DevCouncil/dev map"); got != "DevCouncil/dev map" {
		t.Fatalf("NormalizeAllowlistCommand rewrote a repo path: %q", got)
	}
	if got := NormalizeAllowlistCommand(".venv/bin/dev map"); got != "dev map" {
		t.Fatalf("a bin-directory dev binary should normalise, got %q", got)
	}
}

func TestSplitCommandChain(t *testing.T) {
	tests := []struct {
		input string
		want  []string
	}{
		{"git status", []string{"git status"}},
		{"cd repo && dev map", []string{"cd repo", "dev map"}},
		{"echo 'a && b' && ls -la", []string{"echo 'a && b'", "ls -la"}},
		{`echo "a || b" || true`, []string{`echo "a || b"`, "true"}},
		{"cmd1 ; cmd2 | cmd3", []string{"cmd1", "cmd2", "cmd3"}},
		{"", nil},
	}
	for _, tc := range tests {
		got := SplitCommandChain(tc.input)
		if len(got) != len(tc.want) {
			t.Errorf("SplitCommandChain(%q) = %v, want %v", tc.input, got, tc.want)
			continue
		}
		for i := range got {
			if got[i] != tc.want[i] {
				t.Errorf("SplitCommandChain(%q)[%d] = %q, want %q", tc.input, i, got[i], tc.want[i])
			}
		}
	}
}

func TestCompoundCommandChaining(t *testing.T) {
	gate := CommandGate{
		GlobalAllowedCommands: []string{"npm test"},
		HardRules:             true,
	}
	task := &dc.Task{
		ID:              "TASK-001",
		AllowedCommands: []string{"go test ./...", "git status"},
	}

	// Allowed chain: cd repo && go test ./...
	if d := gate.EvaluateCommand("cd repo && go test ./...", task); d.Blocked() {
		t.Fatalf("cd repo && go test ./... should be allowed, got %+v", d)
	}

	// Denied chain: cd repo && rm -rf /
	if d := gate.EvaluateCommand("cd repo && rm -rf /", task); !d.Blocked() {
		t.Fatalf("cd repo && rm -rf / must be denied, got %+v", d)
	}

	// Git safety denial in chain: git status && git push -f origin main
	if d := gate.EvaluateCommand("git status && git push -f origin main", task); !d.Blocked() || d.Rule != RuleCommandForcePush {
		t.Fatalf("git status && git push -f must be blocked by git safety, got %+v", d)
	}
}
